services:
  - type: web
    name: django-country-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn django_country_api.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_country_api.settings
      - key: PYTHON_VERSION
        value: 3.11
